blank_issues_enabled: true
contact_links:
  - name: Discord-server
    url: https://discord.guncraft.nl
    about: Hier kun je contact leggen met stafleden door middel van een ticket.
  - name: Discord-account
    url: https://discordapp.com/users/366622006059204609
    about: Hier kun je contact leggen met stafleden, zonder in de Discord-server te hoeven zitten.
